<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="Juhis-MacBook-Air.local" failures="1" tests="5" name="/Users/juhikohale/Downloads/FrameworkFromScratch" time="20.292" errors="0" timestamp="2024-03-01T12:08:51 IST">
  <testcase classname="org.ErrorValidationTest" name="LoginErrorValidationTest" time="1.003">
    <skipped/>
  </testcase> <!-- LoginErrorValidationTest -->
  <testcase classname="org.ErrorValidationTest" name="LoginErrorValidationTest" time="0.283">
    <failure type="junit.framework.ComparisonFailure" message="expected:&amp;lt;......&amp;gt; but was:&amp;lt;...or...&amp;gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<......> but was:<...or...>
at junit.framework.Assert.assertEquals(Assert.java:81)
at junit.framework.Assert.assertEquals(Assert.java:87)
at org.ErrorValidationTest.LoginErrorValidationTest(ErrorValidationTest.java:21)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:249)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- LoginErrorValidationTest -->
  <testcase classname="org.ErrorValidationTest" name="productErrorValidation" time="2.005"/>
  <testcase classname="org.submitOrderTest" name="submitProductOrder" time="2.959"/>
  <testcase classname="org.submitOrderTest" name="submitProductOrder" time="3.194"/>
  <testcase classname="org.submitOrderTest" name="orderHistoryTest" time="0.0">
    <ignored/>
  </testcase> <!-- orderHistoryTest -->
</testsuite> <!-- /Users/juhikohale/Downloads/FrameworkFromScratch -->
